version: '3'
services:
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - '5433:5432'
    volumes:
      - ./bin/sql/docker/01_init.sql:/docker-entrypoint-initdb.d/init.sql
